FROM nvidia/cudagl:10.1-devel-ubuntu18.04
#git install時にtime zoneの選択で止まってしまうので先に環境変数を設定
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update  
RUN apt-get install -y python3 python3-pip git cmake libgl1-mesa-dev libglib2.0-0 libsm6 libxrender1 libxext6 fontconfig
RUN pip3 install -U pip 

RUN pip3 install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install opencv-python==4.2.0.32 vispy==0.6.4 moviepy==1.0.2 transforms3d==0.3.1  networkx==2.3 scipy pyyaml matplotlib scikit-image sklearn
RUN pip3 install PyOpenGL PyOpenGL-accelerate 
RUN apt-get install freeglut3-dev -y
WORKDIR /LFmesh

ENV LIBRARY_PATH /usr/local/cuda/lib64/stubs
